#!/bin/bash

# 本地文件管理
remote_host=wangzh@warmcode.net
remote_repo_path=/data/res/in
local_repo_path=/media/hd0/repository/00
local_temp_path=temp

download_lock=.download.lock
retrieve_lock=.retrieve.lock

REDIS_PWD='abc123'
REDIS_CMD="/soft/redis/redis-master/bin/redis-cli -a ${REDIS_PWD}"

redis_set(){
	dkey="$1";
	dval="$2";
	${REDIS_CMD} set "${dkey}" "${dval}" 2>/dev/null;
}

redis_get(){
	dkey="${1}";
	${REDIS_CMD} get "${dkey}" 2>/dev/null;
}

# 同步远程下载的文件
sync(){
	if [ -e ${download_lock} ]; then
	    echo "download process is already running now!";
	    return;
	fi
	
	touch ${download_lock};

	files=$(ssh ${remote_host} "ls ${remote_repo_path}");
	for file in ${files[*]}
	do
		scp "${remote_host}:${remote_repo_path}/${file}" "${local_temp_path}/${file}"
		if [ $? -eq 0 ]; then
		    rmd5=$(ssh ${remote_host} "md5sum ${remote_repo_path}/${file}" | awk '{print $1}');
			lmd5=$(md5sum "temp/${file}" | awk '{print $1}');
			if [ "${lmd5}" == "${rmd5}" ]; then
			   mv ${local_temp_path}/${file} ${local_repo_path}
			   ssh ${remote_host} "rm ${remote_repo_path}/${file}";

			   dkey=$(echo ${file} | grep '[0-9a-z\-]\{36\}' -o);
			   dval="${local_repo_path}/${file}";

			   redis_set "${dkey}" "${dval}";
			   echo "${dkey} : ${dval}";
			fi
		fi
	done

	rm ${download_lock}
}

usage(){
    echo "Usage: $0 [options]";
	echo "  -s 同步远程下载文件";
	echo "  -r 提取仓库文件";
	echo "  -k 根据关键字提取文件";
	echo "  -j 根据文档清单删除文件";
}

basepath=$(cd `dirname $0`;pwd);
cd ${basepath}

while getopts "srkj" opt; do
    case ${opt} in
		s){
			sync;
			exit;
		};;
		r) {
			if [ -e ${retrieve_lock} ]; then
				echo "retrieve process is already running now!";
			else
				touch ${retrieve_lock};
				download;
				rm ${retrieve_lock}
			fi
			exit;
			exit
		};;
		k) {
			echo "get file with keyword.";
			exit;
		};;
		j) {
			echo "remove file from list";
			exit ;
			exit;
		};;
	esac
done

usage;
